export const POLYGON_TWAB_SUBGRAPH_URL = 'https://api.thegraph.com/subgraphs/name/pooltogether/polygon-twab'
export const MAINNET_TWAB_SUBGRAPH_URL = 'https://api.thegraph.com/subgraphs/name/pooltogether/mainnet-twab'
export const RINKEBY_TWAB_SUBGRAPH_URL = 'https://api.thegraph.com/subgraphs/name/pooltogether/rinkeby-twab'
export const MUMBAI_TWAB_SUBGRAPH_URL = 'https://api.thegraph.com/subgraphs/name/pooltogether/mumbai-twab'
export const AVALANCHE_TWAB_SUBGRAPH_URL = 'https://api.thegraph.com/subgraphs/name/pooltogether/avalanche-twab'
