import {
  MAINNET_USDC_PRIZE_DISTRIBUTOR_ADDRESS,
  AVALANCHE_USDC_PRIZE_DISTRIBUTOR_ADDRESS,
  POLYGON_USDC_PRIZE_DISTRIBUTOR_ADDRESS,
  OPTIMISM_MAINNET_USDC_PRIZE_DISTRIBUTOR_ADDRESS,
  OPTIMISM_KOVAN_USDC_PRIZE_DISTRIBUTOR_ADDRESS,
  RINKEBY_TOKENOMICS_PRIZE_DISTRIBUTOR_ADDRESS,
  MAINNET_USDC_TICKET_ADDRESS,
  POLYGON_USDC_TICKET_ADDRESS,
  AVALANCHE_USDC_TICKET_ADDRESS,
  OPTIMISM_MAINNET_USDC_TICKET_ADDRESS,
  OPTIMISM_KOVAN_USDC_TICKET_ADDRESS,
  RINKEBY_USDC5_TICKET_ADDRESS,
  RINKEBY_DAI10_TICKET_ADDRESS,
  RINKEBY_USDC15_TICKET_ADDRESS,
} from '../constants';

function getPrizeDistributorAddress(chainId: string | number, ticket: string): string {
  if (chainId === '1' && ticket === MAINNET_USDC_TICKET_ADDRESS) {
    return MAINNET_USDC_PRIZE_DISTRIBUTOR_ADDRESS;
  }

  if (chainId === '137' && ticket === POLYGON_USDC_TICKET_ADDRESS) {
    return POLYGON_USDC_PRIZE_DISTRIBUTOR_ADDRESS;
  }

  if (chainId === '43114' && ticket === AVALANCHE_USDC_TICKET_ADDRESS) {
    return AVALANCHE_USDC_PRIZE_DISTRIBUTOR_ADDRESS;
  }

  if (chainId === '10' && ticket === OPTIMISM_MAINNET_USDC_TICKET_ADDRESS) {
    return OPTIMISM_MAINNET_USDC_PRIZE_DISTRIBUTOR_ADDRESS;
  }

  if (
    chainId === '4' &&
    (ticket === RINKEBY_USDC5_TICKET_ADDRESS ||
      ticket === RINKEBY_DAI10_TICKET_ADDRESS ||
      ticket === RINKEBY_USDC15_TICKET_ADDRESS)
  ) {
    return RINKEBY_TOKENOMICS_PRIZE_DISTRIBUTOR_ADDRESS;
  }

  if (chainId === '69' && ticket === OPTIMISM_KOVAN_USDC_TICKET_ADDRESS) {
    return OPTIMISM_KOVAN_USDC_PRIZE_DISTRIBUTOR_ADDRESS;
  }

  throw new Error(
    `prize distributor address not defined for chainId: ${chainId} and ticket: ${ticket}`,
  );
}

export default getPrizeDistributorAddress;
